#
version: 2
jobs:
  build:
    # docker:
      # specify the version you desire here
      # - image: circleci/node:8.11
      # - image: circleci/node:latest-browsers

    # working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "branch.sh" }}

      - run: bash -x prepare.sh 

      - save_cache:
          paths:
            - icu
          key: v1-dependencies-{{ checksum "branch.sh" }}

      - run: docker run --rm -v `pwd`:/src trzeci/emscripten bash -c "(cd icu/icu4c/source && bash -x ../../../build.sh)"
