#
version: 2
jobs:
  build:
    machine: true
    # docker:
      # specify the version you desire here
      # - image: circleci/node:8.11
      # - image: circleci/node:latest-browsers

    # working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

      - run: cd wasm-libicu && npm run build && npm pack

      - save_cache:
          paths:
            - wasm-libicu
          key: wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

